version: '3'

services:
  webserver-nginx:
    build: .
    container_name: webserver-nginx
    volumes: 
      - ./mywebsite:/usr/share/nginx/html
   # restart: always
    environment:
      - WEBVERSION=1.0
    ports:
      - "7777:80"